modules:
  https_ready:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_status_codes: [200]
      follow_redirects: false
      fail_if_not_ssl: true
      preferred_ip_protocol: ip4
      fail_if_body_not_matches_regexp: ['"status"\s*:\s*"ready"']
